### ISSUE TITLE
Chrome瀏覽器無法顯示 Embed Report

### ISSUE THREAD

**Issue by sdwh** [MicrosoftDocs/powerbi-docs.zh-tw#2]
參考範例的用法，可以正常在IE瀏覽器呈現，但無法在Chrome呈現。
Console顯示以下訊息：

powerbiportal.dependencies.externals.bundle.js:51 Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at e.getData (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.common.bundle.js:45:9229)
    at new t (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.common.bundle.js:43:23583)
    at Object.&lt;anonymous&gt; (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.common.bundle.js:47:22267)
    at Object.invoke (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:52:8)
    at Object.$get (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:49:205)
    at Object.invoke (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:52:8)
    at https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:53:315
    at d (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:51:1)
    at e (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:51:242)
    at Object.invoke (https://mycompany.com.tw/powerbi/libs/scripts/powerbiportal.dependencies.externals.bundle.js:51:327)
mycompany.com.tw/views/reportServerHost.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
powerbiportal.dependencies.externals.bundle.js:129 Error: [$compile:tpload] http://errors.angularjs.org/1.5.9/$compile/tpload?p0=views%2FreportServerHost.html&p1=404&p2=Not%20Found
    at powerbiportal.dependencies.externals.bundle.js:16
    at powerbiportal.dependencies.externals.bundle.js:168
    at powerbiportal.dependencies.externals.bundle.js:142
    at m.$eval (powerbiportal.dependencies.externals.bundle.js:156)
    at m.$digest (powerbiportal.dependencies.externals.bundle.js:153)
    at m.$apply (powerbiportal.dependencies.externals.bundle.js:157)
    at powerbiportal.dependencies.externals.bundle.js:149
    at e (powerbiportal.dependencies.externals.bundle.js:55)
    at powerbiportal.dependencies.externals.bundle.js:58

請問是否有處理的方法？謝謝

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4f0c4f04-7975-0f89-d5db-7b3e3a5b42f6
* Version Independent ID: b2c4c36e-c00e-ba79-8dc6-df56c696be2c
* Content: [使用 iFrame 來內嵌報告 - Power BI](https://docs.microsoft.com/zh-tw/power-bi/report-server/quickstart-embed#feedback)
* Content Source: [powerbi-docs/report-server/quickstart-embed.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-tw/blob/live/powerbi-docs/report-server/quickstart-embed.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by LisandroSu** [comment]
您好，@sdwh，

非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。
 
請使用 DOCS   頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。

若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。
 
我們由衷感謝您對文章的貢獻。

順頌時祺
Microsoft DOCS 國際小組
